/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/explain/default': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Explanation Endpoint */
    post: operations['explainDefaultPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/score/embedding': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Score Embedding Endpoint */
    post: operations['scoreEmbeddingPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/score/fuzz-detection': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Score Fuzz Detection Endpoint */
    post: operations['scoreFuzzDetectionPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ExplainDefaultRequest
     * @description Request model for generating explanations of neuron/feature behavior
     */
    ExplainDefaultRequest: {
      /**
       * Activations
       * @description List of activation records to analyze
       */
      activations: components['schemas']['NPActivation'][];
      /**
       * Model
       * @description Model identifier to use for explanation generation
       */
      model: string;
      /**
       * Openrouterkey
       * @description API key for OpenRouter service
       */
      openrouterKey: string;
    };
    /**
     * ExplainDefaultResponse
     * @description A natural-language explanation of what the given activations have in common
     */
    ExplainDefaultResponse: {
      /**
       * Explanation
       * @description The generated explanation for the given set of activations
       */
      explanation: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * NPActivation
     * @description An activation record containing tokens and their corresponding activation values
     */
    NPActivation: {
      /**
       * Tokens
       * @description List of tokens for this text
       */
      tokens: string[];
      /**
       * Values
       * @description Activation values corresponding to each token
       */
      values: number[];
    };
    /**
     * ScoreEmbeddingBreakdownItem
     * @description One scored example from an embedding run. With exception of fixing similarity to change to number instead of array of number, type is copied from https://github.com/EleutherAI/sae-auto-interp/blob/3659ff3bfefbe2628d37484e5bcc0087a5b10a27/sae_auto_interp/scorers/embedding/embedding.py#L20
     */
    ScoreEmbeddingBreakdownItem: {
      /**
       * Distance
       * @description Quantile or neighbor distance
       */
      distance: number;
      /**
       * Similarity
       * @description What is the similarity of the example to the explanation
       */
      similarity: number;
      /**
       * Text
       * @description The text that was used to evaluate the similarity
       */
      text: string;
    };
    /**
     * ScoreEmbeddingRequest
     * @description Request model for scoring explanations using embedding similarity
     */
    ScoreEmbeddingRequest: {
      /**
       * Activations
       * @description List of activation records to analyze
       */
      activations: components['schemas']['NPActivation'][];
      /**
       * Explanation
       * @description The explanation to evaluate
       */
      explanation: string;
    };
    /**
     * ScoreEmbeddingResponse
     * @description An embedding-similarity score, with the per-example results it was computed from
     */
    ScoreEmbeddingResponse: {
      /**
       * Breakdown
       * @description Detailed breakdown of the embedding outputs
       */
      breakdown: components['schemas']['ScoreEmbeddingBreakdownItem'][];
      /**
       * Score
       * @description The score from 0 to 1
       */
      score: number;
    };
    /**
     * ScoreFuzzDetectionBreakdownItem
     * @description One scored example from a fuzz or detection run. Type copied from https://github.com/EleutherAI/sae-auto-interp/blob/3659ff3bfefbe2628d37484e5bcc0087a5b10a27/sae_auto_interp/scorers/classifier/sample.py#L19
     */
    ScoreFuzzDetectionBreakdownItem: {
      /**
       * Activations
       * @description List of floats
       */
      activations?: number[] | null;
      /**
       * Correct
       * @description Whether the prediction is correct
       * @default false
       */
      correct: boolean | null;
      /**
       * Distance
       * @description Quantile or neighbor distance
       */
      distance?: number | null;
      /**
       * Groundtruth
       * @description Whether the example is activating or not
       */
      groundTruth?: boolean | null;
      /**
       * Highlighted
       * @description Whether the sample is highlighted
       * @default false
       */
      highlighted: boolean | null;
      /**
       * Prediction
       * @description Whether the model predicted the example activating or not
       * @default false
       */
      prediction: boolean | null;
      /**
       * Probability
       * @description The probability of the example activating
       * @default 0
       */
      probability: number | null;
      /**
       * Strtokens
       * @description List of strings
       */
      strTokens?: string[] | null;
    };
    /**
     * ScoreFuzzDetectionRequest
     * @description Request model for scoring explanations using fuzzing or detection methods
     */
    ScoreFuzzDetectionRequest: {
      /**
       * Activations
       * @description List of activation records to analyze
       */
      activations: components['schemas']['NPActivation'][];
      /**
       * Explanation
       * @description The explanation to evaluate
       */
      explanation: string;
      /**
       * Model
       * @description Model identifier to use for scoring
       */
      model: string;
      /**
       * Openrouterkey
       * @description API key for OpenRouter service
       */
      openrouterKey: string;
      type: components['schemas']['ScoreFuzzDetectionType'];
    };
    /**
     * ScoreFuzzDetectionResponse
     * @description A fuzz or detection score, with the per-example results it was computed from
     */
    ScoreFuzzDetectionResponse: {
      /** Breakdown */
      breakdown: components['schemas']['ScoreFuzzDetectionBreakdownItem'][];
      /**
       * Score
       * @description The score from 0 to 1
       */
      score: number;
    };
    /**
     * ScoreFuzzDetectionType
     * @description Type of scoring method, either fuzz or detection
     * @enum {string}
     */
    ScoreFuzzDetectionType: 'FUZZ' | 'DETECTION';
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  explainDefaultPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "activations": [
         *         {
         *           "tokens": [
         *             "The",
         *             "cat",
         *             "sat",
         *             "on",
         *             "the",
         *             "mat"
         *           ],
         *           "values": [
         *             0,
         *             0.8,
         *             0,
         *             0,
         *             0,
         *             0
         *           ]
         *         },
         *         {
         *           "tokens": [
         *             "I",
         *             " like",
         *             " felines"
         *           ],
         *           "values": [
         *             0,
         *             0,
         *             0.9
         *           ]
         *         }
         *       ],
         *       "model": "openai/gpt-4o-mini",
         *       "openrouter_key": "YOUR_OPENROUTER_KEY"
         *     }
         */
        'application/json': components['schemas']['ExplainDefaultRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExplainDefaultResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  scoreEmbeddingPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ScoreEmbeddingRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScoreEmbeddingResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  scoreFuzzDetectionPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ScoreFuzzDetectionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScoreFuzzDetectionResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
