/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/check-busy': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Check Busy
     * @description Check if the server is currently busy processing a request.
     */
    get: operations['check_busy_check_busy_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/forward-pass': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Forward Pass Handler
     * @description Handle forward pass requests to get salient logits
     */
    post: operations['forward_pass_handler_forward_pass_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/generate-graph': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate Graph */
    post: operations['generate_graph_generate_graph_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/parse-chat-prompt': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Parse Chat Prompt Handler
     * @description Recover structured chat turns from a rendered prompt string.
     *
     *     Deliberately does NOT take ``request_lock``: this is tokenizer-only string
     *     work with no GPU involvement, and the webapp calls it while opening a modal,
     *     so a graph generation in flight must not turn it into a 503.
     *
     *     ``prompt`` echoes back the BOS-stripped input. A non-chat prompt has no
     *     ``messages`` to carry the strip, and the caller wants to put the string back
     *     in an editor, so returning it here is what keeps the BOS literal out of the
     *     frontend.
     *
     *     ``unsteerable_positions`` is the set ``/steer`` will silently drop features
     *     at, computed here the same way and from the same normalized prompt. A steer
     *     UI needs it to know which sliders would do nothing; without it the client has
     *     to guess from token strings, which is the token knowledge this endpoint
     *     exists to keep server-side.
     */
    post: operations['parse_chat_prompt_handler_parse_chat_prompt_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/steer': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Steer Handler
     * @description Handle steer requests
     */
    post: operations['steer_handler_steer_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** CheckBusyResponse */
    CheckBusyResponse: {
      /** Busy */
      busy: boolean;
    };
    /** ForwardPassRequest */
    ForwardPassRequest: {
      /**
       * Desired Logit Prob
       * @default 0.95
       */
      desired_logit_prob: number;
      /**
       * Max N Logits
       * @default 10
       */
      max_n_logits: number;
      /** Messages */
      messages?: components['schemas']['GraphChatMessage'][] | null;
      /**
       * Prompt
       * @default
       */
      prompt: string;
    };
    /**
     * ForwardPassResponse
     * @description The salient-logit payload.
     *
     *     A failed pass returns ``{"error": ...}`` with a 200 instead of this, which the spec does
     *     not describe -- callers check for ``error`` before reading any of these fields. Keeping
     *     that shape out of the model is what lets the five fields below stay required.
     */
    ForwardPassResponse: {
      /** Cumulative Probability */
      cumulative_probability: number;
      /** Input Tokens */
      input_tokens: string[];
      /** Prompt */
      prompt: string;
      /** Salient Logits */
      salient_logits: components['schemas']['SalientLogit'][];
      /** Total Salient Tokens */
      total_salient_tokens: number;
    };
    /**
     * GraphChatMessage
     * @description One structured chat turn.
     *
     *     Roles come back canonical rather than as the template's literal label, so a gemma
     *     ``model`` turn is reported as ``assistant``.
     */
    GraphChatMessage: {
      /** Content */
      content: string;
      /** Role */
      role: string;
    };
    /** GraphGenerationRequest */
    GraphGenerationRequest: {
      /**
       * Batch Size
       * @default 48
       */
      batch_size: number;
      /**
       * Compress
       * @default false
       */
      compress: boolean;
      /**
       * Desired Logit Prob
       * @default 0.95
       */
      desired_logit_prob: number;
      /**
       * Edge Threshold
       * @default 0.98
       */
      edge_threshold: number;
      /**
       * Enable Qk Tracing
       * @default false
       */
      enable_qk_tracing: boolean;
      /**
       * Max Feature Nodes
       * @default 10000
       */
      max_feature_nodes: number;
      /**
       * Max N Logits
       * @default 10
       */
      max_n_logits: number;
      /** Messages */
      messages?: components['schemas']['GraphChatMessage'][] | null;
      /** Model Id */
      model_id: string;
      /**
       * Node Threshold
       * @default 0.8
       */
      node_threshold: number;
      /**
       * Prompt
       * @default
       */
      prompt: string;
      /**
       * Qk Top Fraction
       * @default 0.6
       */
      qk_top_fraction: number;
      /**
       * Qk Topk
       * @default 10
       */
      qk_topk: number;
      /** Signed Url */
      signed_url?: string | null;
      /** Slug Identifier */
      slug_identifier: string;
      /** User Id */
      user_id?: string | null;
    };
    /**
     * GraphGenerationResponse
     * @description The receipt from an upload.
     *
     *     Only describes the ``signed_url`` path, which is the only one the webapp uses. Called
     *     without a ``signed_url`` the endpoint returns the ``circuit_tracer`` graph model itself,
     *     whose schema is not ours to publish (see the module docstring).
     */
    GraphGenerationResponse: {
      /** Error */
      error?: string | null;
      /** Success */
      success?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** LogitsByToken */
    LogitsByToken: {
      /** Token */
      token: string;
      /** Top Logits */
      top_logits: components['schemas']['TopLogit'][];
    };
    /** ParseChatPromptRequest */
    ParseChatPromptRequest: {
      /** Prompt */
      prompt: string;
    };
    /** ParseChatPromptResponse */
    ParseChatPromptResponse: {
      /** Is Chat */
      is_chat: boolean;
      /** Messages */
      messages: components['schemas']['GraphChatMessage'][] | null;
      /** Prompt */
      prompt: string;
      /** Unsteerable Positions */
      unsteerable_positions: number[];
    };
    /** SalientLogit */
    SalientLogit: {
      /** Probability */
      probability: number;
      /** Token */
      token: string;
      /** Token Id */
      token_id: number;
    };
    /**
     * SteerFeature
     * @description One feature intervention.
     *
     *     These field names are public: ``/api/steer-logits`` documents them in its swagger and
     *     forwards the array here untouched, so renaming one is an API break.
     */
    SteerFeature: {
      /**
       * Ablate
       * @default false
       */
      ablate: boolean;
      /** Delta */
      delta?: number | null;
      /** Index */
      index: number;
      /** Layer */
      layer: number;
      /**
       * Steer Generated Tokens
       * @default false
       */
      steer_generated_tokens: boolean;
      /** Steer Position */
      steer_position?: number | null;
      /** Token Active Position */
      token_active_position: number;
    };
    /** SteerRequest */
    SteerRequest: {
      /** Features */
      features: components['schemas']['SteerFeature'][];
      /**
       * Freeze Attention
       * @default false
       */
      freeze_attention: boolean;
      /**
       * Freq Penalty
       * @default 0
       */
      freq_penalty: number;
      /** Messages */
      messages?: components['schemas']['GraphChatMessage'][] | null;
      /** Model Id */
      model_id: string;
      /**
       * N Tokens
       * @default 10
       */
      n_tokens: number;
      /**
       * Prompt
       * @default
       */
      prompt: string;
      /** Seed */
      seed?: number | null;
      /**
       * Temperature
       * @default 0
       */
      temperature: number;
      /**
       * Top K
       * @default 5
       */
      top_k: number;
    };
    /**
     * SteerResponse
     * @description Default and steered generations, plus per-token logits for each.
     *
     *     The SCREAMING_SNAKE keys are the wire names, so they are spelled out as aliases rather than
     *     left to the field names: ``/api/steer-logits`` returns this object nearly verbatim and its
     *     swagger documents them in this form.
     */
    SteerResponse: {
      /** Default Generation */
      DEFAULT_GENERATION: string;
      /** Default Logits By Token */
      DEFAULT_LOGITS_BY_TOKEN: components['schemas']['LogitsByToken'][];
      /** Steered Generation */
      STEERED_GENERATION: string;
      /** Steered Logits By Token */
      STEERED_LOGITS_BY_TOKEN: components['schemas']['LogitsByToken'][];
    };
    /** TopLogit */
    TopLogit: {
      /** Prob */
      prob: number;
      /** Token */
      token: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  check_busy_check_busy_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CheckBusyResponse'];
        };
      };
    };
  };
  forward_pass_handler_forward_pass_post: {
    parameters: {
      query?: never;
      header?: {
        'x-secret-key'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ForwardPassRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ForwardPassResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  generate_graph_generate_graph_post: {
    parameters: {
      query?: never;
      header?: {
        'x-secret-key'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GraphGenerationRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GraphGenerationResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  parse_chat_prompt_handler_parse_chat_prompt_post: {
    parameters: {
      query?: never;
      header?: {
        'x-secret-key'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ParseChatPromptRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ParseChatPromptResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  steer_handler_steer_post: {
    parameters: {
      query?: never;
      header?: {
        'x-secret-key'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SteerRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SteerResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
