/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Check */
    get: operations['healthGet'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/initialize': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Initialize */
    post: operations['initializePost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/activation/all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activation All */
    post: operations['activationAllPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/activation/all-batch': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activation All Batch */
    post: operations['activationAllBatchPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/activation/attention': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activation Attention */
    post: operations['activationAttentionPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/activation/raw': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activation Raw */
    post: operations['activationRawPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/activation/single': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activation Single */
    post: operations['activationSinglePost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/activation/single-batch': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activation Single Batch */
    post: operations['activationSingleBatchPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/activation/source': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activation Source */
    post: operations['activationSourcePost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/activation/topk-by-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activation Topk By Token */
    post: operations['activationTopkByTokenPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/activation/topk-by-token-batch': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activation Topk By Token Batch */
    post: operations['activationTopkByTokenBatchPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/apply-chat-template': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Apply Chat Template */
    post: operations['applyChatTemplatePost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/capabilities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Capabilities
     * @description Report the loaded model, backend, concurrency/token limits, and feature support.
     */
    get: operations['capabilitiesGet'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/lens/prompt': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Lens Prompt */
    post: operations['lensPromptPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/steer/completion': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Completion */
    post: operations['steerCompletionPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/steer/completion-chat': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Completion Chat */
    post: operations['steerCompletionChatPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/steer/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health Check
     * @description Get health stats for the vLLM engine.
     *
     *     Returns GPU memory usage, system RAM, active requests, threads, etc.
     *     Useful for debugging hanging requests.
     */
    get: operations['steerHealthGet'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/tokenize': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Tokenize */
    post: operations['tokenizePost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/util/sae-topk-by-decoder-cossim': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sae Topk By Decoder Cossim */
    post: operations['utilSaeTopkByDecoderCossimPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/util/sae-vector': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sae Vector */
    post: operations['utilSaeVectorPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/util/similarity-matrix-pred': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Similarity Matrix */
    post: operations['utilSimilarityMatrixPredPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ActivationAllBatchRequest
     * @description For a given batch of prompts, get the top activating features for a set of SAEs (eg gemmascope-res-65k), or specific SAEs in the set of SAEs (eg 0-gemmascope-res-65k, 5-gemmascope-res-65k). Also has other customization options.
     */
    ActivationAllBatchRequest: {
      /**
       * Ignorebos
       * @description Whether or not to include features whose highest activation value is the BOS token.
       */
      ignoreBos: boolean;
      /**
       * Model
       * @description Name of the model to test activations on
       */
      model: string;
      /**
       * Numresults
       * @description Optional. The number of top features to return.
       * @default 25
       */
      numResults: number | null;
      /**
       * Prompts
       * @description Input text prompts to get activations for
       */
      prompts: string[];
      /**
       * Selectedsources
       * @description List of specific SAEs to get activations for (eg ["0-gemmascope-res-65k", "5-gemmascope-res-65k"]). If not specified, will get activations for all SAEs in the source set.
       */
      selectedSources: string[];
      /**
       * Sortbytokenindexes
       * @description Sort the results by the sum of the activations at the specified token indexes.
       */
      sortByTokenIndexes: number[];
      /**
       * Sourceset
       * @description The source set name of the SAEs (eg gemmascope-res-16k)
       */
      sourceSet: string;
    };
    /**
     * ActivationAllBatchResponse
     * @description Response for NPActivationAllBatchRequest. Contains the batch results of activations for each top feature and the tokenized prompts.
     */
    ActivationAllBatchResponse: {
      /** Results */
      results: components['schemas']['ActivationAllBatchResult'][];
    };
    /**
     * ActivationAllBatchResult
     * @description One prompt's result within a batched top-features request.
     */
    ActivationAllBatchResult: {
      /** Activations */
      activations: components['schemas']['ActivationAllFeature'][];
      /**
       * Counts
       * @description Not currently supported and may be incorrect. This is the number of features that activated by layer, starting from layer 0 of this SAE. Need to be redesigned.
       */
      counts?: number[][] | null;
      /** Tokens */
      tokens: string[];
    };
    /**
     * ActivationAllFeature
     * @description One feature and its activation in an NPActivationAllResponse
     */
    ActivationAllFeature: {
      /** Dfamaxvalue */
      dfaMaxValue?: number | null;
      /** Dfatargetindex */
      dfaTargetIndex?: number | null;
      /** Dfavalues */
      dfaValues?: number[] | null;
      /** Index */
      index: number;
      /** Maxvalue */
      maxValue: number;
      /** Maxvalueindex */
      maxValueIndex: number;
      /** Source */
      source: string;
      /** Sumvalues */
      sumValues?: number | null;
      /** Values */
      values: number[];
    };
    /**
     * ActivationAllRequest
     * @description For a given prompt, get the top activating features for a set of SAEs (eg gemmascope-res-65k), or specific SAEs in the set of SAEs (eg 0-gemmascope-res-65k, 5-gemmascope-res-65k). Also has other customization options.
     */
    ActivationAllRequest: {
      /**
       * Ignorebos
       * @description Whether or not to include features whose highest activation value is the BOS token.
       */
      ignoreBos: boolean;
      /**
       * Model
       * @description Name of the model to test activations on
       */
      model: string;
      /**
       * Numresults
       * @description Optional. The number of top features to return.
       * @default 25
       */
      numResults: number | null;
      /**
       * Prompt
       * @description Input text prompt to get activations for
       */
      prompt: string;
      /**
       * Selectedsources
       * @description List of specific SAEs to get activations for (eg ["0-gemmascope-res-65k", "5-gemmascope-res-65k"]). If not specified, will get activations for all SAEs in the source set.
       */
      selectedSources: string[];
      /**
       * Sortbytokenindexes
       * @description Sort the results by the sum of the activations at the specified token indexes.
       */
      sortByTokenIndexes: number[];
      /**
       * Sourceset
       * @description The source set name of the SAEs (eg gemmascope-res-16k)
       */
      sourceSet: string;
    };
    /**
     * ActivationAllResponse
     * @description Response for NPActivationAllRequest. Contains activations for each top feature and the tokenized prompt.
     */
    ActivationAllResponse: {
      /** Activations */
      activations: components['schemas']['ActivationAllFeature'][];
      /**
       * Counts
       * @description Not currently supported and may be incorrect. This is the number of features that activated by layer, starting from layer 0 of this SAE. Need to be redesigned.
       */
      counts?: number[][] | null;
      /** Tokens */
      tokens: string[];
    };
    /**
     * ActivationAttentionRequest
     * @description Attention pattern for one (layer, head) of the model.
     */
    ActivationAttentionRequest: {
      /** Head */
      head: number;
      /** Layer */
      layer: number;
      /** Model */
      model: string;
      /** Prompt */
      prompt: string;
    };
    /**
     * ActivationAttentionResponse
     * @description A sparse COO attention matrix for one head.
     *
     *     Only the top keys per query row survive, each encoded as a flat ``q * seq_len + k``
     *     index, so the two arrays are index-aligned with each other rather than with the tokens.
     */
    ActivationAttentionResponse: {
      /** Attentionindices */
      attentionIndices: number[];
      /** Attentionvalues */
      attentionValues: number[];
      /** Maxactivation */
      maxActivation: number;
      /** Seqlen */
      seqLen: number;
      /** Tokens */
      tokens: string[];
    };
    /**
     * ActivationRawLayer
     * @description The captured vectors for one layer of one prompt.
     */
    ActivationRawLayer: {
      /** Layer */
      layer: number;
      /** Tokenindices */
      tokenIndices: number[];
      /** Values */
      values: number[][];
    };
    /**
     * ActivationRawPromptResult
     * @description One prompt's tokens and its per-layer captured vectors.
     */
    ActivationRawPromptResult: {
      /** Activations */
      activations: components['schemas']['ActivationRawLayer'][];
      /** Tokenids */
      tokenIds: number[];
      /** Tokenstrings */
      tokenStrings: string[];
    };
    /**
     * ActivationRawRequest
     * @description Residual-stream vectors at each prompt's final token, with no SAE involved.
     */
    ActivationRawRequest: {
      /**
       * Hookpoint
       * @default residual_stream
       */
      hookPoint: string;
      /** Layers */
      layers?: number[] | null;
      /** Model */
      model?: string | null;
      /** Prompts */
      prompts: string[];
      /**
       * Type
       * @default final_output_token
       */
      type: string;
    };
    /**
     * ActivationRawResponse
     * @description Raw capture results, echoing the capture settings they were produced under.
     */
    ActivationRawResponse: {
      /** Device */
      device: string;
      /** Dtype */
      dtype: string;
      /** Hookpoint */
      hookPoint: string;
      /** Results */
      results: components['schemas']['ActivationRawPromptResult'][];
      /** Type */
      type: string;
    };
    /**
     * ActivationSingleBatchRequest
     * @description Get activations for either a specific feature in an SAE (specified by "source" + "index") or a custom vector (specified by "vector" + "hook")
     */
    ActivationSingleBatchRequest: {
      /**
       * Hook
       * @description Hook that the custom vector applies to. Must be specified with "vector".
       */
      hook?: string | null;
      /**
       * Index
       * @description Index of the SAE. Must be specified with "source", or not at all.
       */
      index?: string | null;
      /**
       * Model
       * @description Name of the model to test activations on
       */
      model: string;
      /**
       * Prompts
       * @description Input text prompts to get activations for
       */
      prompts: string[];
      /**
       * Source
       * @description Source identifier - could be an SAE ID (eg 5-gemmascope-res-16k). Must be specified with "index", or not at all.
       */
      source?: string | null;
      /**
       * Vector
       * @description Custom vector to test activations. Must be specified with "hook".
       */
      vector?: number[] | null;
    };
    /**
     * ActivationSingleBatchResponse
     * @description Response for NPActivationBatchRequest. Contains the batch results of activation values and tokenized prompt.
     */
    ActivationSingleBatchResponse: {
      /** Results */
      results: components['schemas']['ActivationSingleBatchResult'][];
    };
    /**
     * ActivationSingleBatchResult
     * @description One prompt's result within a batched single-feature request.
     */
    ActivationSingleBatchResult: {
      activation: components['schemas']['ActivationValues'];
      /** Tokens */
      tokens: string[];
      /**
       * Tokensisspecial
       * @description Index-aligned with "tokens". True where the token is one of the tokenizer's special tokens (BOS, EOS, padding, chat turn markers, and so on) rather than content. Lets a client filter scaffolding without knowing any model family's token literals.
       */
      tokensIsSpecial: boolean[];
    };
    /**
     * ActivationSingleRequest
     * @description Get activations for either a specific feature in an SAE (specified by "source" + "index") or a custom vector (specified by "vector" + "hook")
     */
    ActivationSingleRequest: {
      /**
       * Hook
       * @description Hook that the custom vector applies to. Must be specified with "vector".
       */
      hook?: string | null;
      /**
       * Index
       * @description Index of the SAE. Must be specified with "source", or not at all.
       */
      index?: string | null;
      /**
       * Model
       * @description Name of the model to test activations on
       */
      model: string;
      /**
       * Prompt
       * @description Input text prompt to get activations for
       */
      prompt: string;
      /**
       * Source
       * @description Source identifier - could be an SAE ID (eg 5-gemmascope-res-16k). Must be specified with "index", or not at all.
       */
      source?: string | null;
      /**
       * Vector
       * @description Custom vector to test activations. Must be specified with "hook".
       */
      vector?: number[] | null;
    };
    /**
     * ActivationSingleResponse
     * @description Response for NPActivationSingleRequest. Contains the activation values and tokenized prompt.
     */
    ActivationSingleResponse: {
      activation: components['schemas']['ActivationValues'];
      /** Tokens */
      tokens: string[];
      /**
       * Tokensisspecial
       * @description Index-aligned with "tokens". True where the token is one of the tokenizer's special tokens (BOS, EOS, padding, chat turn markers, and so on) rather than content. Lets a client filter scaffolding without knowing any model family's token literals.
       */
      tokensIsSpecial: boolean[];
    };
    /**
     * ActivationSourceRequest
     * @description For a given prompt, get the top activating features for a source (eg 0-gemmascope-res-65k or 5-gemmascope-res-65k), and return the results as a 3D array of prompt x prompt_token x feature_index.
     */
    ActivationSourceRequest: {
      /**
       * Model
       * @description Name of the model to test activations on
       */
      model: string;
      /**
       * Prompts
       * @description Input text prompt to get activations for
       */
      prompts: string[];
      /**
       * Source
       * @description The source (eg 5-gemmascope-res-16k)
       */
      source: string;
    };
    /**
     * ActivationSourceResponse
     * @description All prompts results, only including non-zero features and non-zero activations
     */
    ActivationSourceResponse: {
      /** Results */
      results: components['schemas']['ActivationSourceResult'][];
    };
    /**
     * ActivationSourceResult
     * @description One prompt's results, only including non-zero values and non-zero activations
     */
    ActivationSourceResult: {
      /**
       * Activefeatures
       * @description Dictionary mapping feature indices to arrays of [token_index, activation_value]
       */
      activeFeatures?: {
        [key: string]: number[][];
      } | null;
      /**
       * Tokens
       * @description The prompt, tokenized.
       */
      tokens: string[];
    };
    /**
     * ActivationTopkByTokenBatchRequest
     * @description Get activations for either a specific feature in an SAE (specified by "source" + "index") or a custom vector (specified by "vector" + "hook")
     */
    ActivationTopkByTokenBatchRequest: {
      /**
       * Ignorebos
       * @description Whether or not to include features whose highest activation value is the BOS token.
       */
      ignoreBos: boolean;
      /**
       * Model
       * @description Name of the model to test activations on
       */
      model: string;
      /**
       * Prompts
       * @description Input text prompts to get activations for
       */
      prompts: string[];
      /**
       * Source
       * @description Source identifier - could be an SAE ID (eg 5-gemmascope-res-16k). Must be specified with "index", or not at NPActivationAllRequest.
       */
      source: string;
      /**
       * Topk
       * @description The number of features to include for each token position.
       */
      topK?: number | null;
    };
    /**
     * ActivationTopkByTokenBatchResponse
     * @description Response for NPActivationTopkByTokenBatchRequest. Contains the batch results of top features at each token position and the tokenized prompts.
     */
    ActivationTopkByTokenBatchResponse: {
      /** Results */
      results: components['schemas']['ActivationTopkByTokenBatchResult'][];
    };
    /**
     * ActivationTopkByTokenBatchResult
     * @description One prompt's result within a batched topk-by-token request.
     */
    ActivationTopkByTokenBatchResult: {
      /** Results */
      results: components['schemas']['ActivationTopkByTokenResult'][];
      /** Tokens */
      tokens: string[];
    };
    /**
     * ActivationTopkByTokenFeature
     * @description One feature active at a single token position.
     */
    ActivationTopkByTokenFeature: {
      /**
       * Activationvalue
       * @description The activation value of this feature at this token position.
       */
      activationValue: number;
      /**
       * Featureindex
       * @description The index of the feature in the SAE.
       */
      featureIndex: number;
    };
    /**
     * ActivationTopkByTokenRequest
     * @description Get activations for either a specific feature in an SAE (specified by "source" + "index") or a custom vector (specified by "vector" + "hook")
     */
    ActivationTopkByTokenRequest: {
      /**
       * Ignorebos
       * @description Whether or not to include features whose highest activation value is the BOS token.
       */
      ignoreBos: boolean;
      /**
       * Model
       * @description Name of the model to test activations on
       */
      model: string;
      /**
       * Prompt
       * @description Input text prompt to get activations for
       */
      prompt: string;
      /**
       * Source
       * @description Source identifier - could be an SAE ID (eg 5-gemmascope-res-16k). Must be specified with "index", or not at NPActivationAllRequest.
       */
      source: string;
      /**
       * Topk
       * @description The number of features to include for each token position.
       */
      topK?: number | null;
    };
    /**
     * ActivationTopkByTokenResponse
     * @description Response for NPActivationTopkByTokenRequest.
     */
    ActivationTopkByTokenResponse: {
      /** Results */
      results: components['schemas']['ActivationTopkByTokenResult'][];
      /** Tokens */
      tokens: string[];
    };
    /**
     * ActivationTopkByTokenResult
     * @description One token's TopK result, including its top features.
     */
    ActivationTopkByTokenResult: {
      /**
       * Isspecial
       * @description Whether this token is one of the tokenizer's special tokens (BOS, EOS, padding, chat turn markers, and so on) rather than content. Lets a client filter scaffolding without knowing any model family's token literals.
       */
      isSpecial: boolean;
      /**
       * Token
       * @description The token string
       */
      token: string;
      /**
       * Tokenposition
       * @description The index of the token in the prompt.
       */
      tokenPosition: number;
      /** Topfeatures */
      topFeatures: components['schemas']['ActivationTopkByTokenFeature'][];
    };
    /**
     * ActivationValues
     * @description One feature's activation over a prompt, plus its DFA attribution if computed.
     */
    ActivationValues: {
      /** Dfamaxvalue */
      dfaMaxValue?: number | null;
      /** Dfatargetindex */
      dfaTargetIndex?: number | null;
      /** Dfavalues */
      dfaValues?: number[] | null;
      /** Maxvalue */
      maxValue: number;
      /** Maxvalueindex */
      maxValueIndex: number;
      /** Values */
      values: number[];
    };
    /**
     * ApplyChatTemplateRequest
     * @description Messages to render, plus the template switches to render them under.
     */
    ApplyChatTemplateRequest: {
      /**
       * Addgenerationprompt
       * @default true
       */
      addGenerationPrompt: boolean;
      /**
       * Chattemplatekwargs
       * @default {}
       */
      chatTemplateKwargs: {
        [key: string]: unknown;
      };
      /** Messages */
      messages: components['schemas']['ChatMessage'][];
    };
    /**
     * ApplyChatTemplateResponse
     * @description The rendered prompt, its token ids, and the per-token span metadata.
     */
    ApplyChatTemplateResponse: {
      /** Prompt */
      prompt: string;
      /** Spans */
      spans: components['schemas']['TokenSpan'][];
      /** Tokens */
      tokens: number[];
    };
    /**
     * ChatMessage
     * @description One message to render through the model's chat template.
     */
    ChatMessage: {
      /** Channel */
      channel?: string | null;
      /** Content */
      content: string;
      /** Role */
      role: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * HealthResponse
     * @description Liveness only -- says the process is up, not that a model finished loading.
     */
    HealthResponse: {
      /** Status */
      status: string;
    };
    /**
     * LensChatMessage
     * @description One message of a chat-formatted lens prompt.
     */
    LensChatMessage: {
      /** Content */
      content: string;
      /** Role */
      role: string;
    };
    /**
     * LensPromptRequest
     * @description Everything one lens run needs: what to read out, where, and how to intervene.
     */
    LensPromptRequest: {
      /**
       * Cachedtokenids
       * @default []
       */
      cachedTokenIds: number[];
      /** Chat */
      chat?: components['schemas']['LensChatMessage'][] | null;
      /**
       * Enablethinking
       * @default false
       */
      enableThinking: boolean;
      /**
       * Failifbusy
       * @default false
       */
      failIfBusy: boolean;
      /**
       * Filternonwordtokens
       * @default true
       */
      filterNonWordTokens: boolean;
      /**
       * Inputtokenids
       * @default []
       */
      inputTokenIds: number[];
      /**
       * Layers
       * @default []
       */
      layers: number[];
      /** Maxseqlen */
      maxSeqLen?: number | null;
      /** Model */
      model: string;
      /**
       * Numcompletiontokens
       * @default 0
       */
      numCompletionTokens: number;
      /**
       * Prependbos
       * @default true
       */
      prependBos: boolean;
      /**
       * Preservethinking
       * @default true
       */
      preserveThinking: boolean;
      /** Prompt */
      prompt?: string | null;
      /**
       * Steerablate
       * @default false
       */
      steerAblate: boolean;
      /**
       * Steergeneratedtokens
       * @default false
       */
      steerGeneratedTokens: boolean;
      /**
       * Steerlayers
       * @default []
       */
      steerLayers: number[];
      /**
       * Steerstrength
       * @default 0
       */
      steerStrength: number;
      /**
       * Steertokens
       * @default []
       */
      steerTokens: components['schemas']['LensSteerToken'][];
      /**
       * Stream
       * @default true
       */
      stream: boolean;
      swapToken?: components['schemas']['LensSteerToken'] | null;
      /**
       * Temperature
       * @default 1
       */
      temperature: number;
      /**
       * Topn
       * @default 10
       */
      topN: number;
      /** Type */
      type: components['schemas']['LensType'][];
    };
    /**
     * LensSteerToken
     * @description A single readout to steer on.
     *
     *     ``token`` is the EXACT decoded token string (whitespace preserved, e.g.
     *     ``" cat"``) as it appeared in a read-out slice; the server resolves it back
     *     to a vocab id via a cached reverse-decode map. ``type`` selects which lens's
     *     readout direction to use: ``JACOBIAN_LENS`` uses the J-lens direction
     *     ``J_bar_l^T @ w_t`` at each fitted layer (the residual-space direction whose
     *     J-lens readout is this token), ``LOGIT_LENS`` uses the plain unembedding
     *     direction ``w_t``.
     */
    LensSteerToken: {
      /** Token */
      token: string;
      type: components['schemas']['LensType'];
    };
    /**
     * LensType
     * @description Which lens's readout direction to use.
     * @enum {string}
     */
    LensType: 'LOGIT_LENS' | 'JACOBIAN_LENS';
    /**
     * NPAxis
     * @description A readout axis supplied with the request, rather than named by id from this server's assets.
     *
     *     Either send `source` on its own, or send `direction` and `layer` with as much of the rest as
     *     the axis has. With everything else defaulted the reading is the dot product of the direction
     *     with the mean residual-stream activation over each assistant turn, which is the axis you can
     *     build without a calibration corpus. The optional fields refine that in three steps::
     *
     *         h          = mean resid_post activation over the assistant turn, at `layer`
     *         x          = h - preNormMean                    # default: no-op
     *         x          = x / max(||x||, 1e-12)              # only when normalize is "l2"
     *         raw        = dot(x - postNormMean, direction)
     *         value      = (raw - center) / (raw >= center ? scalePos : scaleNeg)
     *         percentile = interpolated against quantilesPos / quantilesNeg, bounded to [-1, 1]
     *
     *     So `value` is in the axis's own units until `center` and the two scales put it on a readable
     *     one, and a `percentile` is reported only once the quantile tables say what the fitting corpus
     *     looked like. `value` is never clipped: a reading past 1 says the axis is being read off the
     *     distribution it was fitted on, which is a signal rather than something to pin to the boundary.
     *
     *     Nothing here says whether a pole is one you would rather see. That is an editorial call about
     *     a trait rather than a property of a fit, so it belongs to whatever displays the reading.
     */
    NPAxis: {
      /**
       * Author
       * @description Who fitted this axis. Reported as-is
       */
      author?: string | null;
      /**
       * Caveat
       * @description A known limitation, worth showing beside this axis's values
       */
      caveat?: string | null;
      /**
       * Center
       * @description Where the axis reads zero, in raw projection units
       * @default 0
       */
      center: number;
      /**
       * Direction
       * @description The fitted direction. Required without `source`, and must be the model's hidden size
       */
      direction?: number[] | null;
      /**
       * Displayname
       * @description A label for an axis whose two poles are not one. Nothing parses it
       */
      displayName?: string | null;
      /**
       * Id
       * @description What this axis is reported under, and unique across `axes` and `customAxes` in one request. Conventionally `<author>_<name>`, though nothing here parses it.
       */
      id: string;
      /**
       * Layer
       * @description Layer to read `resid_post` at. Required without `source`
       */
      layer?: number | null;
      /** @default none */
      normalize: components['schemas']['NPAxisNormalize'];
      /**
       * Polenegative
       * @description Name of the - pole, e.g. "respectful"
       */
      poleNegative?: string | null;
      /** Polenegativedescription */
      poleNegativeDescription?: string | null;
      /**
       * Polepositive
       * @description Name of the + pole, e.g. "toxic"
       */
      polePositive?: string | null;
      /** Polepositivedescription */
      polePositiveDescription?: string | null;
      /**
       * Postnormmean
       * @description Subtracted after normalizing. Interchangeable with `preNormMean` when normalize is none
       */
      postNormMean?: number[] | null;
      /**
       * Prenormmean
       * @description Subtracted from the activation before normalizing. Rarely needed
       */
      preNormMean?: number[] | null;
      /**
       * Quantilelevels
       * @description Levels the two tables are sampled at. Defaults to evenly spaced 0 to 1
       */
      quantileLevels?: number[] | null;
      /** Quantilesneg */
      quantilesNeg?: number[] | null;
      /**
       * Quantilespos
       * @description Distance from `center` at each level of this pole's half of the fitting corpus, ascending. Sent with `quantilesNeg`, and the two are what a percentile is read off.
       */
      quantilesPos?: number[] | null;
      render?: components['schemas']['NPAxisRender'];
      /**
       * Scaleneg
       * @description Divisor below `center`. May not be zero
       * @default 1
       */
      scaleNeg: number;
      /**
       * Scalepos
       * @description Divisor above `center`. May not be zero
       * @default 1
       */
      scalePos: number;
      /** @description Fetch the axis from a published artifact instead of sending it inline */
      source?: components['schemas']['NPAxisSource'] | null;
    };
    /**
     * NPAxisNormalize
     * @description How an activation is scaled before it is projected onto a readout axis.
     * @enum {string}
     */
    NPAxisNormalize: 'l2' | 'none';
    /**
     * NPAxisRender
     * @description How a conversation has to be templated for an axis's numbers to mean anything.
     *
     *     A projection onto a fitted direction only holds if the conversation reaches the model rendered
     *     the way it was during fitting, so these conditions travel with the axis. They are applied
     *     before generation and so change the text itself, which is why every axis in one request has to
     *     agree about them.
     */
    NPAxisRender: {
      /**
       * Blanksystemprompt
       * @description The fit used an empty system turn, so a caller-supplied system prompt is blanked before rendering.
       * @default false
       */
      blankSystemPrompt: boolean;
      /**
       * Templatekwargs
       * @description Extra keyword arguments for the chat template. Llama 3.1 injects the current date into its system block, so a fit on that model pins `date_string` or drifts off distribution as the calendar moves.
       */
      templateKwargs?: {
        [key: string]: string;
      };
    };
    /**
     * NPAxisSource
     * @description A published axis to fetch, instead of sending its vectors inline.
     *
     *     The artifact is one folder holding `axis.yaml` and `axis.safetensors`. Everything about the
     *     axis comes from there, so nothing but `id` may be sent beside this.
     */
    NPAxisSource: {
      /**
       * Hffolder
       * @description Folder within that repo holding the two files
       */
      hfFolder: string;
      /**
       * Hfrepoid
       * @description Hugging Face model repo, e.g. "neuronpedia/persona-axes"
       */
      hfRepoId: string;
      /**
       * Revision
       * @description Branch, tag or commit sha to read. Defaults to the repo's default branch, and the commit it resolved to comes back as `sourceRevision` on the readout -- an artifact that changes under you changes what its readings mean, so pin one to compare across time.
       */
      revision?: string | null;
    };
    /**
     * NPFeature
     * @description A feature in Neuronpedia, identified by model, source, and index.
     */
    NPFeature: {
      /** Index */
      index: number;
      /** Model */
      model: string;
      /** Source */
      source: string;
    };
    /**
     * NPLogprob
     * @description What the model was weighing at one position of the output
     */
    NPLogprob: {
      /**
       * Logprob
       * @description Natural log of the probability of the emitted token
       */
      logprob: number;
      /**
       * Token
       * @description The token that was actually emitted, as text
       */
      token: string;
      /**
       * Toplogprobs
       * @description The highest-scoring candidates at this position, most likely first
       */
      topLogprobs: components['schemas']['NPLogprobTop'][];
    };
    /**
     * NPLogprobTop
     * @description One token the model considered at a single position
     */
    NPLogprobTop: {
      /**
       * Logprob
       * @description Natural log of the probability the model gave this candidate
       */
      logprob: number;
      /**
       * Token
       * @description The candidate token, as text
       */
      token: string;
    };
    /**
     * NPSteerChatMessage
     * @description One message in a steered chat exchange.
     */
    NPSteerChatMessage: {
      /**
       * Content
       * @description The chat message
       */
      content: string;
      /**
       * Role
       * @description The role of the message (eg "model", "user", etc)
       */
      role: string;
    };
    /**
     * NPSteerChatResult
     * @description The formatted and unformatted ("raw") chat messages
     */
    NPSteerChatResult: {
      /** Chattemplate */
      chatTemplate: components['schemas']['NPSteerChatMessage'][];
      /**
       * Logprobs
       * @description Per-token scores for the generated text, in output order. Absent unless logprobs were both requested and reported by the serving backend, so read its absence as "not available" rather than "no candidates".
       */
      logprobs?: components['schemas']['NPLogprob'][] | null;
      /** Raw */
      raw: string;
      type?: components['schemas']['NPSteerType'] | null;
    };
    /**
     * NPSteerCompletionOutput
     * @description A streamed steering/default response. Output is either the whole response or a chunk, depending on response type.
     */
    NPSteerCompletionOutput: {
      /**
       * Logprobs
       * @description Per-token scores for the generated text, in output order. Absent unless logprobs were both requested and reported by the serving backend, so read its absence as "not available" rather than "no candidates".
       */
      logprobs?: components['schemas']['NPLogprob'][] | null;
      /** Output */
      output: string;
      type: components['schemas']['NPSteerType'];
    };
    /**
     * NPSteerFeature
     * @description An SAE feature to steer with, and how hard.
     */
    NPSteerFeature: {
      /** Index */
      index: number;
      /** Model */
      model: string;
      /** Source */
      source: string;
      /** Steeringvector */
      steeringVector?: number[] | null;
      /** Strength */
      strength: number;
    };
    /**
     * NPSteerMethod
     * @description How a steering vector is combined with the residual stream.
     * @enum {string}
     */
    NPSteerMethod: 'SIMPLE_ADDITIVE' | 'ORTHOGONAL_DECOMP' | 'PROJECTION_CAP';
    /**
     * NPSteerType
     * @description Whether a given output was produced with steering applied or without it.
     * @enum {string}
     */
    NPSteerType: 'STEERED' | 'DEFAULT';
    /**
     * NPSteerVector
     * @description A raw vector for steering, including its hook and strength
     */
    NPSteerVector: {
      /** Hook */
      hook: string;
      /** Steeringvector */
      steeringVector: number[];
      /** Strength */
      strength: number;
    };
    /**
     * SimilarityMatrixRequest
     * @description Predicted similarity matrix for one feature over a piece of text.
     */
    SimilarityMatrixRequest: {
      /** Index */
      index: number;
      /** Modelid */
      modelId: string;
      /** Sourceid */
      sourceId: string;
      /** Text */
      text: string;
    };
    /**
     * SimilarityMatrixResponse
     * @description Token-by-token cosine similarities, with the BOS token dropped from both axes.
     */
    SimilarityMatrixResponse: {
      /** Similaritymatrix */
      similarityMatrix: number[][];
      /** Tokens */
      tokens: string[];
    };
    /**
     * SteerAxisReadout
     * @description One axis read across the assistant's turns, for one steer type.
     *
     *     Keyed by `id` rather than by `title`: a title is a display string that may be reworded,
     *     and these readouts are persisted by callers.
     */
    SteerAxisReadout: {
      /**
       * Author
       * @description Who fitted this axis; the `<author>_` prefix of `id`
       */
      author: string;
      /**
       * Caveat
       * @description A known limitation of this axis, worth showing beside its values
       */
      caveat?: string | null;
      /**
       * Id
       * @description Axis id, as requested in `axes` or `customAxes`
       */
      id: string;
      /**
       * Layer
       * @description Layer the axis was fitted and read at
       */
      layer?: number | null;
      /**
       * Polenegative
       * @description What a negative reading means, e.g. "respectful"
       */
      poleNegative?: string | null;
      /** Polenegativedescription */
      poleNegativeDescription?: string | null;
      /**
       * Polepositive
       * @description What a positive reading means, e.g. "toxic". Absent when the axis names no poles
       */
      polePositive?: string | null;
      /** Polepositivedescription */
      polePositiveDescription?: string | null;
      /**
       * Sourcerevision
       * @description The commit this axis was read from, for an axis fetched with `source`. What makes a reading reproducible: the same revision is the same axis, whatever the branch has moved on to since.
       */
      sourceRevision?: string | null;
      /**
       * Title
       * @description Display label for the axis
       */
      title: string;
      /** Turns */
      turns?: components['schemas']['SteerAxisTurn'][] | null;
      type?: components['schemas']['NPSteerType'] | null;
    };
    /**
     * SteerAxisTurn
     * @description One assistant turn's reading on a single axis, as a measurement and as a percentile.
     *
     *     `value` is calibrated against the axis's own spread, so it passes 1 for roughly 2% of turns
     *     by construction and is never clipped -- how far past the calibration corpus a turn sits is
     *     what says an axis is being read off distribution. `percentile` is the same reading expressed
     *     as the share of that corpus it is past, which cannot leave [-1, 1]. Display the percentile
     *     and keep the value: a gauge reading "102%" looks broken, and a clipped value would delete
     *     the diagnostic. `percentile` is absent for an axis whose asset ships no quantile tables.
     */
    SteerAxisTurn: {
      /**
       * Percentile
       * @description Where `value` falls in the axis's calibration corpus, signed by pole and bounded to [-1, 1]: 0.97 is further along this pole than 97% of that corpus. Absent when the axis ships no quantile tables.
       */
      percentile?: number | null;
      /**
       * Percentilepostcap
       * @description `percentile` for this turn measured under steering (post-cap)
       */
      percentilePostCap?: number | null;
      /**
       * Snippet
       * @description Truncated conversation content for this turn
       */
      snippet?: string | null;
      /**
       * Value
       * @description Axis value for this turn (pre-cap)
       */
      value?: number | null;
      /**
       * Valuepostcap
       * @description Axis value for this turn measured under steering (post-cap)
       */
      valuePostCap?: number | null;
    };
    /**
     * SteerCompletionChatRequest
     * @description Steer a chat exchange rather than a bare completion.
     */
    SteerCompletionChatRequest: {
      /**
       * Customaxes
       * @description Readout axes to report for the generated turns, sent inline or fetched from a published artifact. This server ships none of its own, so every axis a request wants measured is named and defined here. Two entries sharing an id is a 400.
       */
      customAxes?: components['schemas']['NPAxis'][] | null;
      /**
       * Features
       * @description Features to steer towards or away from
       */
      features?: components['schemas']['NPSteerFeature'][] | null;
      /** Freqpenalty */
      freqPenalty: number;
      /**
       * Model
       * @description Name of the model
       */
      model: string;
      /**
       * Ncompletiontokens
       * @description Number of completion tokens to generate
       */
      nCompletionTokens: number;
      /**
       * Nlogprobs
       * @description How many candidate tokens to report for each generated position. 0 asks for none. Backends that cannot report scores omit `logprobs` whatever this is set to.
       * @default 0
       */
      nLogprobs: number | null;
      /** Normalizesteering */
      normalizeSteering: boolean;
      /**
       * Prompt
       * @description Array of chat messages to pass to the model
       */
      prompt: components['schemas']['NPSteerChatMessage'][];
      /** Seed */
      seed: number;
      steerMethod: components['schemas']['NPSteerMethod'];
      /** Steerspecialtokens */
      steerSpecialTokens: boolean;
      /**
       * Stream
       * @description Whether or not to stream responses using Server Side Events (SSE). Note that the OpenAPI spec does not support SSE - you will receive multiple responses with the same format as non-streaming, except with the "output" field chunked.
       * @default false
       */
      stream: boolean | null;
      /**
       * Strengthmultiplier
       * @description The steering strength will be multiplied by this number
       */
      strengthMultiplier: number;
      /** Temperature */
      temperature: number;
      /**
       * Types
       * @description Array that specifies whether or not to generate STEERED output, DEFAULT (non-steered) output, or both.
       */
      types: components['schemas']['NPSteerType'][];
      /** Vectors */
      vectors?: components['schemas']['NPSteerVector'][] | null;
    };
    /**
     * SteerCompletionChatResponse
     * @description The steering/default chat responses.
     */
    SteerCompletionChatResponse: {
      /**
       * Axes
       * @description Axis readouts for the assistant turns, one entry per requested axis per steer type
       */
      axes?: components['schemas']['SteerAxisReadout'][] | null;
      input: components['schemas']['NPSteerChatResult'];
      /** Outputs */
      outputs: components['schemas']['NPSteerChatResult'][];
    };
    /**
     * SteerCompletionRequest
     * @description Base request for steering
     */
    SteerCompletionRequest: {
      /**
       * Features
       * @description Features to steer towards or away from
       */
      features?: components['schemas']['NPSteerFeature'][] | null;
      /** Freqpenalty */
      freqPenalty: number;
      /**
       * Model
       * @description Name of the model
       */
      model: string;
      /**
       * Ncompletiontokens
       * @description Number of completion tokens to generate
       */
      nCompletionTokens: number;
      /**
       * Nlogprobs
       * @description How many candidate tokens to report for each generated position. 0 asks for none. Backends that cannot report scores omit `logprobs` whatever this is set to.
       * @default 0
       */
      nLogprobs: number | null;
      /** Normalizesteering */
      normalizeSteering: boolean;
      /**
       * Prompt
       * @description Text to pass the model for completion
       */
      prompt: string;
      /** Seed */
      seed: number;
      steerMethod: components['schemas']['NPSteerMethod'];
      /**
       * Stream
       * @description Whether or not to stream responses using Server Side Events (SSE). Note that the OpenAPI spec does not support SSE - you will receive multiple responses with the same format as non-streaming, except with the "output" field chunked.
       * @default false
       */
      stream: boolean | null;
      /**
       * Strengthmultiplier
       * @description The steering strength will be multiplied by this number
       */
      strengthMultiplier: number;
      /** Temperature */
      temperature: number;
      /**
       * Types
       * @description Array that specifies whether or not to generate STEERED output, DEFAULT (non-steered) output, or both.
       */
      types: components['schemas']['NPSteerType'][];
      /** Vectors */
      vectors?: components['schemas']['NPSteerVector'][] | null;
    };
    /**
     * SteerCompletionResponse
     * @description The steering/default responses.
     */
    SteerCompletionResponse: {
      /** Outputs */
      outputs: components['schemas']['NPSteerCompletionOutput'][];
    };
    /**
     * TokenSpan
     * @description One rendered token and the message it belongs to.
     */
    TokenSpan: {
      /** Channel */
      channel: string | null;
      /** Messageindex */
      messageIndex: number | null;
      /** Position */
      position: number;
      /** Role */
      role: string | null;
      /** Section */
      section: string;
      /** Tokenid */
      tokenId: number;
      /** Tokenstr */
      tokenStr: string;
    };
    /**
     * TokenizeRequest
     * @description Text to split into tokens, plus how to treat the BOS token
     */
    TokenizeRequest: {
      /**
       * Model
       * @description Model whose tokenizer should be used
       */
      model: string;
      /**
       * Prependbos
       * @description Force a beginning-of-sequence token on or off. Omit to follow whatever the model normally does, which is what the other endpoints assume.
       */
      prependBos?: boolean | null;
      /**
       * Text
       * @description Text to split into tokens
       */
      text: string;
    };
    /**
     * TokenizeResponse
     * @description The token ids, their rendered text, and whether BOS was prepended.
     */
    TokenizeResponse: {
      /**
       * Prependbos
       * @description Whether a beginning-of-sequence token was actually prepended
       */
      prependBos: boolean;
      /**
       * Tokenstrings
       * @description The same tokens rendered back to text, index-aligned with `tokens`
       */
      tokenStrings: string[];
      /**
       * Tokens
       * @description One token id per token, in order
       */
      tokens: number[];
    };
    /**
     * UtilSaeTopkByDecoderCossimFeature
     * @description One nearby feature and how close it is.
     */
    UtilSaeTopkByDecoderCossimFeature: {
      /** Cosinesimilarity */
      cosineSimilarity?: number | null;
      feature?: components['schemas']['NPFeature'] | null;
    };
    /**
     * UtilSaeTopkByDecoderCossimRequest
     * @description Find the features whose decoder directions are closest to a feature or vector.
     */
    UtilSaeTopkByDecoderCossimRequest: {
      feature?: components['schemas']['NPFeature'] | null;
      /**
       * Model
       * @description Model to compare the vector or feature against.
       */
      model: string;
      /**
       * Numresults
       * @description Number of top features to return. Clamped to 128, and to the number of features in the source.
       */
      numResults: number;
      /**
       * Source
       * @description Source/SAE ID to compare the vector or feature against.
       */
      source: string;
      /**
       * Vector
       * @description Custom vector to find the top features by cossim for.
       */
      vector?: number[] | null;
    };
    /**
     * UtilSaeTopkByDecoderCossimResponse
     * @description The query feature echoed back, alongside its nearest neighbours.
     */
    UtilSaeTopkByDecoderCossimResponse: {
      feature?: components['schemas']['NPFeature'] | null;
      /** Topkdecodercossimfeatures */
      topkDecoderCossimFeatures?: components['schemas']['UtilSaeTopkByDecoderCossimFeature'][] | null;
    };
    /**
     * UtilSaeVectorRequest
     * @description Get the raw vector for an SAE feature
     */
    UtilSaeVectorRequest: {
      /** Index */
      index: number;
      /** Model */
      model: string;
      /** Source */
      source: string;
    };
    /**
     * UtilSaeVectorResponse
     * @description The decoder vector for one feature, and the hook it belongs to.
     */
    UtilSaeVectorResponse: {
      /** Hookname */
      hookName: string;
      /** Vector */
      vector: number[];
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthGet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  initializePost: {
    parameters: {
      query?: {
        custom_hf_model_id?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  activationAllPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivationAllRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivationAllResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  activationAllBatchPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivationAllBatchRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivationAllBatchResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  activationAttentionPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivationAttentionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivationAttentionResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  activationRawPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivationRawRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivationRawResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  activationSinglePost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivationSingleRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivationSingleResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  activationSingleBatchPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivationSingleBatchRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivationSingleBatchResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  activationSourcePost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivationSourceRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivationSourceResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  activationTopkByTokenPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivationTopkByTokenRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivationTopkByTokenResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  activationTopkByTokenBatchPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivationTopkByTokenBatchRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivationTopkByTokenBatchResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  applyChatTemplatePost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ApplyChatTemplateRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApplyChatTemplateResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  capabilitiesGet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  lensPromptPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LensPromptRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  steerCompletionPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SteerCompletionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SteerCompletionResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  steerCompletionChatPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SteerCompletionChatRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SteerCompletionChatResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  steerHealthGet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  tokenizePost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenizeRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenizeResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  utilSaeTopkByDecoderCossimPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UtilSaeTopkByDecoderCossimRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UtilSaeTopkByDecoderCossimResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  utilSaeVectorPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UtilSaeVectorRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UtilSaeVectorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  utilSimilarityMatrixPredPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SimilarityMatrixRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SimilarityMatrixResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
