/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Root
     * @description Health check.
     */
    get: operations['root__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/compare': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Compare
     * @description Describe the difference between two activation vectors (a - b).
     */
    post: operations['compare_compare_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/completion': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Completion
     * @description Generate a continuation for the prompt and return tokens for the
     *     full (prompt + completion) text. Set `stream=true` to receive tokens
     *     incrementally as SSE events.
     */
    post: operations['completion_completion_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/describe': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Describe
     * @description Describe activation vector(s) in natural language, with optional MSE scores.
     *
     *     Set stream=true to receive partial text updates as SSE events.
     *     Streaming events:
     *       - Partial: {"index": i, "text": "partial...", "done": false}
     *       - Final:   {"index": i, "description": "...", "mse": ..., "cosine_similarity": ...}
     *       - End:     [DONE]
     */
    post: operations['describe_describe_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/explain': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Explain
     * @description Extract activations and describe them in natural language.
     *
     *     If positions is omitted, all token positions are described.
     *     Positions use Python-style indexing (negative values count from end).
     *     Set stream=true to receive results as SSE events.
     *
     *     Up to NLA_MAX_CONCURRENT_EXPLAINS requests run in parallel; the
     *     (N+1)th request gets HTTP 429 (fail-fast, no queueing). Verbalizer
     *     fan-out across all parallel /explains is bounded by NLA_MAX_CONCURRENT
     *     via a server-wide semaphore, so KV-pool occupancy stays capped.
     */
    post: operations['explain_explain_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/extract': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Extract
     * @description Extract per-token activation vectors from the source model.
     */
    post: operations['extract_extract_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/score': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Score
     * @description Score an existing text description against the original activation vector.
     *
     *     The reconstructor forward pass is blocking torch work, so we run it on
     *     a thread-pool executor (via run_in_executor) to keep the FastAPI event
     *     loop responsive — otherwise concurrent /describe streams, /health,
     *     etc. would all stall while a /score is in flight. Concurrency is
     *     capped by NLA_RECONSTRUCTOR_MAX_CONCURRENT to bound VRAM and keep the
     *     executor pool from drowning.
     */
    post: operations['score_score_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tokenize': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Tokenize
     * @description Tokenize text (or structured chat `messages`) using the source model's
     *     tokenizer. When `messages` is provided, the model's chat template is applied
     *     server-side and per-token span metadata is returned.
     */
    post: operations['tokenize_tokenize_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ChatMessageInput */
    ChatMessageInput: {
      /**
       * Channel
       * @description Optional harmony channel (analysis/final/commentary) for assistant turns.
       */
      channel?: string | null;
      /**
       * Content
       * @description Message text
       * @default
       */
      content: string;
      /**
       * Role
       * @description Chat role, e.g. user / assistant / system
       */
      role: string;
    };
    /** CompareRequest */
    CompareRequest: {
      /**
       * Activation A
       * @description First activation vector
       */
      activation_a: number[];
      /**
       * Activation B
       * @description Second activation vector
       */
      activation_b: number[];
      /**
       * Max New Tokens
       * @default 200
       */
      max_new_tokens: number;
      /**
       * Temperature
       * @default 0.7
       */
      temperature: number;
    };
    /** CompareResponse */
    CompareResponse: {
      /** Cosine Similarity */
      cosine_similarity?: number | null;
      /**
       * Description
       * @description Description of the difference vector (a - b)
       */
      description: string;
      /**
       * Diff Norm
       * @description L2 norm of the difference vector
       */
      diff_norm: number;
      /** Mse */
      mse?: number | null;
    };
    /** CompletionRequest */
    CompletionRequest: {
      /**
       * Add Generation Prompt
       * @default true
       */
      add_generation_prompt: boolean;
      /**
       * Completion Tokens
       * @description Number of tokens to generate as continuation (clamped server-side to 1-512).
       * @default 16
       */
      completion_tokens: number;
      /**
       * Continue Final Message
       * @default false
       */
      continue_final_message: boolean;
      /** Enable Thinking */
      enable_thinking?: boolean | null;
      /**
       * Messages
       * @description Structured chat messages. When set, the server applies the model's chat template (ignoring `text`) and returns per-token spans.
       */
      messages?: components['schemas']['ChatMessageInput'][] | null;
      /**
       * Stream
       * @description If true, stream tokens as SSE events instead of returning the full response.
       * @default false
       */
      stream: boolean;
      /**
       * Temperature
       * @default 0.7
       */
      temperature: number;
      /**
       * Text
       * @description Prompt text to extend (or provide `messages`).
       */
      text?: string | null;
    };
    /** DescribeRequest */
    DescribeRequest: {
      /**
       * Activations
       * @description List of activation vectors, each of length d_model
       */
      activations: number[][];
      /**
       * Max New Tokens
       * @default 200
       */
      max_new_tokens: number;
      /**
       * Stream
       * @description Stream results as SSE events
       * @default false
       */
      stream: boolean;
      /**
       * Temperature
       * @default 0.7
       */
      temperature: number;
    };
    /** DescribeResponse */
    DescribeResponse: {
      /** Results */
      results: components['schemas']['DescriptionResult'][];
    };
    /** DescriptionResult */
    DescriptionResult: {
      /**
       * Cosine Similarity
       * @description Cosine similarity (if reconstructor available)
       */
      cosine_similarity?: number | null;
      /** Description */
      description: string;
      /**
       * Mse
       * @description Reconstruction MSE (if reconstructor available)
       */
      mse?: number | null;
    };
    /** ExplainRequest */
    ExplainRequest: {
      /**
       * Add Generation Prompt
       * @default true
       */
      add_generation_prompt: boolean;
      /**
       * Continue Final Message
       * @default false
       */
      continue_final_message: boolean;
      /** Enable Thinking */
      enable_thinking?: boolean | null;
      /**
       * Max New Tokens
       * @description Max tokens for NLA verbalizer explanation
       * @default 200
       */
      max_new_tokens: number;
      /**
       * Messages
       * @description Structured chat messages. When set, the server applies the model's chat template (ignoring `text`) and returns per-token spans.
       */
      messages?: components['schemas']['ChatMessageInput'][] | null;
      /**
       * Positions
       * @description Token positions to describe (Python-style indexing, e.g. [-1] for last). If omitted or empty, all positions are described.
       */
      positions?: number[] | null;
      /**
       * Reverse
       * @description Process token positions in reverse order (last to first)
       * @default true
       */
      reverse: boolean;
      /**
       * Stream
       * @description Stream results as SSE events
       * @default false
       */
      stream: boolean;
      /**
       * Temperature
       * @default 0.7
       */
      temperature: number;
      /**
       * Text
       * @description Input text to extract activations from (or provide `messages`).
       */
      text?: string | null;
    };
    /** ExplainResponse */
    ExplainResponse: {
      /** Layer Index */
      layer_index: number;
      /** Results */
      results: components['schemas']['ExplainResult'][];
    };
    /** ExplainResult */
    ExplainResult: {
      /** Channel */
      channel?: string | null;
      /** Cosine Similarity */
      cosine_similarity?: number | null;
      /** Description */
      description: string;
      /**
       * Fragment Count
       * @default 1
       */
      fragment_count: number;
      /**
       * Fragment Index
       * @default 0
       */
      fragment_index: number;
      /**
       * Generated
       * @description True if this token was generated (not from original input)
       * @default false
       */
      generated: boolean;
      /** L2 Norm */
      l2_norm: number;
      /** Message Index */
      message_index?: number | null;
      /** Mse */
      mse?: number | null;
      /** Position */
      position: number;
      /** Role */
      role?: string | null;
      /** Section */
      section?: string | null;
      /** Token */
      token: string;
      /** Token Id */
      token_id: number;
    };
    /** ExtractRequest */
    ExtractRequest: {
      /**
       * Add Generation Prompt
       * @default true
       */
      add_generation_prompt: boolean;
      /**
       * Continue Final Message
       * @default false
       */
      continue_final_message: boolean;
      /** Enable Thinking */
      enable_thinking?: boolean | null;
      /**
       * Messages
       * @description Structured chat messages. When set, the server applies the model's chat template (ignoring `text`) and returns per-token spans.
       */
      messages?: components['schemas']['ChatMessageInput'][] | null;
      /**
       * Text
       * @description Input text to extract activations from (or provide `messages`).
       */
      text?: string | null;
    };
    /** ExtractResponse */
    ExtractResponse: {
      /** Layer Index */
      layer_index: number;
      /** Tokens */
      tokens: components['schemas']['TokenActivation'][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * HealthLimits
     * @description The request caps this process was configured with, so a client can pre-validate.
     */
    HealthLimits: {
      /** Max Completion Tokens */
      max_completion_tokens: number;
      /** Max Describe Batch */
      max_describe_batch: number;
      /** Max Description Chars */
      max_description_chars: number;
      /** Max Input Chars */
      max_input_chars: number;
      /** Max New Tokens */
      max_new_tokens: number;
      /** Max Positions Per Request */
      max_positions_per_request: number;
    };
    /**
     * HealthResponse
     * @description Liveness plus which components loaded and how they were configured.
     *
     *     Most fields are null until the lifespan finishes, and stay null for whichever of the
     *     verbalizer / reconstructor / source model this process did not load.
     */
    HealthResponse: {
      /** Completion Available */
      completion_available: boolean;
      /** D Model */
      d_model?: number | null;
      /** Extraction Layer */
      extraction_layer?: number | null;
      limits: components['schemas']['HealthLimits'];
      /** Max Concurrent */
      max_concurrent: number;
      /** Max Concurrent Explains */
      max_concurrent_explains: number;
      /** Max Describe Requests */
      max_describe_requests: number;
      /** Num Cuda Devices */
      num_cuda_devices: number;
      /** Reconstructor Available */
      reconstructor_available: boolean;
      /** Reconstructor Device */
      reconstructor_device?: string | null;
      /** Reconstructor Fp8 */
      reconstructor_fp8?: boolean | null;
      /** Reconstructor Int4 */
      reconstructor_int4?: boolean | null;
      /** Reconstructor Max Concurrent */
      reconstructor_max_concurrent: number;
      /** Source Device */
      source_device?: string | null;
      /** Source Fp8 */
      source_fp8?: boolean | null;
      /** Source Max Concurrent */
      source_max_concurrent: number;
      /** Source Model */
      source_model?: string | null;
      /** Source Truncated */
      source_truncated?: boolean | null;
      /** Status */
      status: string;
      /** Verbalizer Cuda Graph Max Bs */
      verbalizer_cuda_graph_max_bs?: number | null;
      /** Verbalizer Device */
      verbalizer_device?: string | null;
      /** Verbalizer Kv Cache Dtype */
      verbalizer_kv_cache_dtype?: string | null;
      /** Verbalizer Model */
      verbalizer_model: string;
      /** Verbalizer Quantization */
      verbalizer_quantization?: string | null;
      /** Verbalizer Torch Compile */
      verbalizer_torch_compile?: boolean | null;
    };
    /** ScoreRequest */
    ScoreRequest: {
      /**
       * Activation
       * @description Original activation vector
       */
      activation: number[];
      /**
       * Description
       * @description Text description to score
       */
      description: string;
    };
    /** ScoreResponse */
    ScoreResponse: {
      /** Cosine Similarity */
      cosine_similarity: number;
      /**
       * Mse
       * @description Reconstruction MSE, range [0, 4]. ~0.2 good, ~1 mediocre, 2 orthogonal
       */
      mse: number;
    };
    /** TokenActivation */
    TokenActivation: {
      /** Activation */
      activation: number[];
      /** L2 Norm */
      l2_norm: number;
      /** Position */
      position: number;
      /** Token */
      token: string;
      /** Token Id */
      token_id: number;
    };
    /** TokenInfo */
    TokenInfo: {
      /** Channel */
      channel?: string | null;
      /**
       * Fragment Count
       * @description Total number of tokens in this byte-fragment run (1 for tokens that decode cleanly on their own). When >1, the `token` string is the merged glyph and is identical for every token in the run.
       * @default 1
       */
      fragment_count: number;
      /**
       * Fragment Index
       * @description 0-based index within a multi-token byte fragment run. 0 for tokens that decode cleanly on their own.
       * @default 0
       */
      fragment_index: number;
      /** Message Index */
      message_index?: number | null;
      /** Position */
      position: number;
      /** Role */
      role?: string | null;
      /**
       * Section
       * @description "header" | "content" | "footer" | "scaffold"
       */
      section?: string | null;
      /** Token */
      token: string;
      /** Token Id */
      token_id: number;
    };
    /** TokenizeRequest */
    TokenizeRequest: {
      /**
       * Add Generation Prompt
       * @default true
       */
      add_generation_prompt: boolean;
      /**
       * Continue Final Message
       * @default false
       */
      continue_final_message: boolean;
      /** Enable Thinking */
      enable_thinking?: boolean | null;
      /**
       * Messages
       * @description Structured chat messages. When set, the server applies the model's chat template (ignoring `text`) and returns per-token spans.
       */
      messages?: components['schemas']['ChatMessageInput'][] | null;
      /**
       * Text
       * @description Input text to tokenize (or provide `messages`).
       */
      text?: string | null;
    };
    /** TokenizeResponse */
    TokenizeResponse: {
      /**
       * Prompt Length
       * @description Number of tokens from the original input text
       */
      prompt_length: number;
      /**
       * Text
       * @description Full text (original + any generated completion)
       */
      text: string;
      /** Tokens */
      tokens: components['schemas']['TokenInfo'][];
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  root__get: {
    parameters: {
      query?: never;
      header?: {
        'x-secret-key'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  compare_compare_post: {
    parameters: {
      query?: never;
      header?: {
        'x-secret-key'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CompareRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CompareResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  completion_completion_post: {
    parameters: {
      query?: never;
      header?: {
        'x-secret-key'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CompletionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenizeResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  describe_describe_post: {
    parameters: {
      query?: never;
      header?: {
        'x-secret-key'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DescribeRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DescribeResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  explain_explain_post: {
    parameters: {
      query?: never;
      header?: {
        'x-secret-key'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ExplainRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExplainResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  extract_extract_post: {
    parameters: {
      query?: never;
      header?: {
        'x-secret-key'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ExtractRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExtractResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  score_score_post: {
    parameters: {
      query?: never;
      header?: {
        'x-secret-key'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ScoreRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScoreResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  tokenize_tokenize_post: {
    parameters: {
      query?: never;
      header?: {
        'x-secret-key'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenizeRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenizeResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
