/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Root
     * @description Health check and model info.
     */
    get: operations['root__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/channel/{channel_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Channel Connections
     * @description Get all neurons that read from or write to a specific residual channel.
     */
    get: operations['get_channel_connections_channel__channel_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/neuron/{layer}/{neuron}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Neuron Connections
     * @description Get circuit traces for a specific MLP neuron.
     *
     *     Returns forward trace (downstream neurons) and backward trace (upstream neurons).
     */
    get: operations['get_neuron_connections_neuron__layer___neuron__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ChannelConnectionsResponse
     * @description Every neuron touching one residual channel, grouped by layer.
     *
     *     The ``*_by_layer`` keys are layer indices. They are ints in python but JSON object keys are
     *     always strings, so they arrive as ``"0"``, ``"1"`` and so on.
     */
    ChannelConnectionsResponse: {
      /** Channel Id */
      channel_id: number;
      /** Readers By Layer */
      readers_by_layer: {
        [key: string]: components['schemas']['ChannelNeuron'][];
      };
      /** Writers By Layer */
      writers_by_layer: {
        [key: string]: components['schemas']['ChannelNeuron'][];
      };
    };
    /**
     * ChannelNeuron
     * @description A neuron reading from or writing to a residual channel, with its weight.
     */
    ChannelNeuron: {
      /** Neuron Id */
      neuron_id: number;
      /** Weight */
      weight: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * HealthResponse
     * @description Liveness plus the dimensions needed to bounds-check a request.
     */
    HealthResponse: {
      /** D Model */
      d_model: number;
      /** Mlp Size */
      mlp_size: number;
      /** Model */
      model: string;
      /** Num Layers */
      num_layers: number;
      /** Status */
      status: string;
    };
    /**
     * NeuronConnectionsResponse
     * @description Circuit traces downstream and upstream of one MLP neuron.
     */
    NeuronConnectionsResponse: {
      /** Layer */
      layer: number;
      /** Neuron */
      neuron: number;
      /** Trace Backward */
      trace_backward: components['schemas']['TraceNode'][];
      /** Trace Forward */
      trace_forward: components['schemas']['TraceNode'][];
    };
    /**
     * TraceNode
     * @description One hop in a circuit trace: a neuron reached through a residual channel.
     *
     *     ``children`` and ``parents`` are the same relationship in opposite directions -- a node in
     *     ``trace_forward`` carries ``children``, one in ``trace_backward`` carries ``parents``, and
     *     never both. They are modelled on one type because every consumer walks the two traces with
     *     the same code.
     */
    TraceNode: {
      /** Children */
      children?: components['schemas']['TraceNode'][] | null;
      /** Layer */
      layer: number;
      /** Neuron */
      neuron: number;
      /** Parents */
      parents?: components['schemas']['TraceNode'][] | null;
      /**
       * Read Weight
       * @description Weight with which this neuron reads the channel
       */
      read_weight: number;
      /**
       * Via Channel
       * @description Residual channel connecting this neuron to the previous hop
       */
      via_channel: number;
      /**
       * Write Weight
       * @description Weight with which the previous hop writes the channel
       */
      write_weight: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  root__get: {
    parameters: {
      query?: never;
      header?: {
        'x-secret-key'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_channel_connections_channel__channel_id__get: {
    parameters: {
      query?: {
        /** @description Number of top neurons to return per layer */
        top_k?: number;
      };
      header?: {
        'x-secret-key'?: string | null;
      };
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChannelConnectionsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_neuron_connections_neuron__layer___neuron__get: {
    parameters: {
      query?: {
        /** @description Depth of circuit trace */
        trace_depth?: number;
        /** @description Top K channels/neurons per step in trace */
        trace_k?: number;
      };
      header?: {
        'x-secret-key'?: string | null;
      };
      path: {
        layer: number;
        neuron: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NeuronConnectionsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
