openapi: 3.0.0
info:
  title: Neuronpedia - Inference Shared Steer
  version: 1.0.0

components:
  schemas:
    NPSteerFeature:
      allOf:
        - $ref: "../../shared.yaml#/components/schemas/NPFeature"
        - type: object
          description: A feature with an additional strength parameter for steering.
          required:
            - strength
          properties:
            strength:
              type: number
              example: 10
            steering_vector:
              type: array
              items:
                type: number

    NPSteerVector:
      type: object
      description: A raw vector for steering, including its hook and strength
      required:
        - steering_vector
        - hook
        - strength
      properties:
        steering_vector:
          type: array
          items:
            type: number
        strength:
          type: number
        hook:
          type: string
          example: blocks.0.hook_resid_pre

    NPSteerType:
      type: string
      enum: ["STEERED", "DEFAULT"]

    NPSteerMethod:
      type: string
      enum: ["SIMPLE_ADDITIVE", "ORTHOGONAL_DECOMP"]

    NPLogprobTop:
      type: object
      description: A single top logprob candidate
      required:
        - token
        - logprob
      properties:
        token:
          type: string
          description: The token string
        logprob:
          type: number
          description: The log probability of this token

    NPLogprob:
      type: object
      description: Logprobs for a single token
      required:
        - token
        - logprob
        - top_logprobs
      properties:
        token:
          type: string
          description: The chosen token
        logprob:
          type: number
          description: The log probability of the chosen token
        top_logprobs:
          type: array
          items:
            $ref: "#/components/schemas/NPLogprobTop"
          description: Top candidate tokens and their log probabilities

    NPSteerCompletionResponseInner:
      type: object
      description: A streamed steering/default response. Output is either the whole response or a chunk, depending on response type. 
      required:
        - type
        - output
      properties:
        type:
          $ref: "#/components/schemas/NPSteerType"
        output:
          type: string
        logprobs:
          type: array
          items:
            $ref: "#/components/schemas/NPLogprob"
          description: Token logprobs for the output sequence. Only present if n_logprobs > 0.

    NPSteerChatMessage:
      type: object
      required:
        - content
        - role
      properties:
        content:
          type: string
          description: The chat message
        role:
          type: string
          description: The role of the message (eg "model", "user", etc)

    NPSteerChatResult:
      type: object
      description: The formatted and unformatted ("raw") chat messages
      required:
        - chat_template
        - raw
      properties:
        chat_template:
          type: array
          items:
            $ref: "#/components/schemas/NPSteerChatMessage"
        raw:
          type: string
        type:
          $ref: "#/components/schemas/NPSteerType"
        logprobs:
          type: array
          items:
            $ref: "#/components/schemas/NPLogprob"
          description: Token logprobs for the output sequence. Only present if n_logprobs > 0.

    SteerCompletionRequest:
      type: object
      description: Base request for steering
      required:
        - prompt
        - model
        - types
        - n_completion_tokens
        - temperature
        - strength_multiplier
        - freq_penalty
        - seed
        - steer_method
        - normalize_steering
      properties:
        prompt:
          type: string
          description: Text to pass the model for completion
          example: "The most iconic structure on Earth is"
        model:
          type: string
          description: Name of the model
          example: "gpt2-small"
        steer_method:
          $ref: "#/components/schemas/NPSteerMethod"
          example: "SIMPLE_ADDITIVE"
        normalize_steering:
          type: boolean
          default: false
          example: false
        types:
          type: array
          items:
            $ref: "#/components/schemas/NPSteerType"
          minItems: 1
          description: Array that specifies whether or not to generate STEERED output, DEFAULT (non-steered) output, or both.
          example: ["STEERED", "DEFAULT"]
        features:
          type: array
          items:
            $ref: "#/components/schemas/NPSteerFeature"
          description: Features to steer towards or away from
          example:
            - model: "gpt2-small"
              source: "9-res-jb"
              index: 1124
              strength: 48
        vectors:
          type: array
          items:
            $ref: "#/components/schemas/NPSteerVector"
        n_completion_tokens:
          type: integer
          minimum: 1
          description: Number of completion tokens to generate
          example: 50
        temperature:
          type: number
          minimum: 0
          example: 0.8
        strength_multiplier:
          type: number
          description: The steering strength will be multiplied by this number
          example: 1.0
        freq_penalty:
          type: number
          example: 0.0
        seed:
          type: number
          example: 42
        stream:
          type: boolean
          description: Whether or not to stream responses using Server Side Events (SSE). Note that the OpenAPI spec does not support SSE - you will receive multiple responses with the same format as non-streaming, except with the "output" field chunked.
          default: false
          example: false
        n_logprobs:
          type: integer
          minimum: 0
          maximum: 10
          default: 0
          description: Number of logprobs to return per token. 0 means no logprobs.
          example: 0
paths: {}
