openapi: 3.0.0

info:
  version: 1.0.0
  title: Neuronpedia - AutoInterp Server
  contact:
    email: johnny@neuronpedia.org
  license:
    name: MIT

servers:
  - url: /v1
    description: Relative URL (requires running on same host)
  - url: http://localhost:5003/v1
    description: Local autointerp server

paths:
  # Explanations
  /explain/default:
    $ref: "autointerp/paths/explain/default.yaml"

  # Scoring
  /score/embedding:
    $ref: "autointerp/paths/score/embedding.yaml"
  /score/fuzz-detection:
    $ref: "autointerp/paths/score/fuzz-detection.yaml"

components:
  securitySchemes:
    SimpleSecretAuth:
      type: apiKey
      in: header
      name: X-SECRET-KEY

security:
  - SimpleSecretAuth: []
