# Originally generated by datamodel-codegen from feature.yaml, which no longer exists in the
# repository, so this is maintained by hand.

from __future__ import annotations

from pydantic import BaseModel, Field


class NPFeature(BaseModel):
    model: str = Field(..., json_schema_extra={"example": "gpt2-small"})
    source: str = Field(..., json_schema_extra={"example": "0-res-jb"})
    index: int = Field(..., json_schema_extra={"example": 14057})
